import re
from pathlib import Path


def make_report(pytest_stdout_path: str = "pytest.out", report_path: str = "report.txt") -> None:

    src = Path(pytest_stdout_path)

    out = Path(report_path)


    text = src.read_text(encoding="utf-8") if src.exists() else ""


    # 例: "2 passed in 0.16s"​

    m = re.search(r"(\d+)\s+passed.*?in\s+([\d\.]+)s", text)

    passed, secs = (m.group(1), m.group(2)) if m else ("?", "?")



    lines = [

        "=== Test Report (pytest) ===",

        f"Passed: {passed}",

        f"Duration(s): {secs}",

        "",

        "Raw tail:",

        "\n".join(text.strip().splitlines()[-10:]),

        "",

        "Generated by generate_report.py",

    ]

    out.write_text("\n".join(lines), encoding="utf-8")

    print(f"Saved: {out.resolve()}")



if __name__ == "__main__":

    make_report()