name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pytest

      - name: Run tests and save output
        run: |
          pytest > pytest.out || true

      - name: Generate report
        run: |
          python githubfile/generate_report.py

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: pytest-report
          path: report.txt
